# Generated by Django 5.1.7 on 2025-04-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recommended_percentage',
        ),
    ]
