# Generated by Django 5.1.7 on 2025-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_category_recommended_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='reminder_type',
            field=models.CharField(choices=[('bill_payment', 'Bill Payment'), ('saving_goals', 'Saving Goals'), ('expenses_entry', 'Expenses Entry'), ('others', 'others')], max_length=20),
        ),
    ]
